=== AleksandrsKondratjevs/test-design-claude/app/code/Scandiweb/ContentTypes/etc/content_type.xsd
<?xml version="1.0"?>
<!--
/**
 * @category  Scandiweb
 * @package   Scandiweb_ContentTypes
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:redefine schemaLocation="urn:magento:framework:Data/etc/argument/types.xsd"/>
    <xs:element name="config">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="type" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element type="xs:string" name="preview_template" minOccurs="0"/>
                            <xs:element type="xs:string" name="master_template" minOccurs="0"/>
                            <xs:element type="parents" name="parents" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="breakpoints" name="breakpoints" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="children" name="children" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="appearances" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="appearance" name="appearance" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="additional_data" name="additional_data" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="xs:string" name="is_system" minOccurs="0"/>
                        </xs:all>
                        <xs:attribute type="xs:string" name="name" use="required"/>
                        <xs:attribute type="xs:string" name="translate" use="optional"/>
                        <xs:attribute type="xs:byte" name="sortOrder" use="optional"/>
                        <xs:attribute type="xs:string" name="label" use="optional"/>
                        <xs:attribute type="xs:string" name="icon" use="optional"/>
                        <xs:attribute type="xs:string" name="component" use="optional"/>
                        <xs:attribute type="xs:string" name="preview_component" use="optional"/>
                        <xs:attribute type="xs:string" name="master_component" use="optional"/>
                        <xs:attribute type="xs:string" name="form" use="optional"/>
                        <xs:attribute type="xs:string" name="menu_section" use="optional"/>
                        <!-- Added additional attribute for passing block class -->
                        <xs:attribute type="xs:string" name="backend_block" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="appearance">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="data" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="name"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element type="elements" name="elements" minOccurs="0" maxOccurs="1"/>
            <xs:element type="converters" name="converters" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="form" minOccurs="0" maxOccurs="1"/>
            <xs:element type="breakpoints" name="breakpoints" minOccurs="0" maxOccurs="1"/>
        </xs:choice>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:boolean" name="default" use="optional"/>
        <xs:attribute type="xs:string" name="preview_template" use="optional"/>
        <xs:attribute type="xs:string" name="master_template" use="optional"/>
        <xs:attribute type="xs:string" name="reader" use="optional"/>
    </xs:complexType>
    <xs:complexType name="parents">
        <xs:sequence>
            <xs:element type="parent" name="parent" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="default_policy" use="optional"/>
    </xs:complexType>
    <xs:complexType name="breakpoints">
        <xs:sequence>
            <xs:element type="breakpoint" name="breakpoint" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="children">
        <xs:sequence>
            <xs:element type="child" name="child" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="default_policy" use="optional"/>
    </xs:complexType>
    <xs:complexType name="parent">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="policy" use="optional"/>
    </xs:complexType>
    <xs:complexType name="breakpoint">
        <xs:choice maxOccurs="unbounded">
            <xs:element type="xs:string" name="form" minOccurs="0" maxOccurs="1"/>
        </xs:choice>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>
    <xs:complexType name="child">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="policy" use="optional"/>
    </xs:complexType>
    <xs:complexType name="elements">
        <xs:sequence>
            <xs:element type="element" name="element" minOccurs="1" maxOccurs="unbounded">
                <xs:unique name="uniqueNames">
                    <xs:annotation>
                        <xs:documentation>
                            Attribute and Style names must be unique
                        </xs:documentation>
                    </xs:annotation>
                    <xs:selector xpath="attribute|style"/>
                    <xs:field xpath="@name"/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="converters">
        <xs:sequence>
            <xs:element type="converter" name="converter" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="converter">
        <xs:sequence>
            <xs:element type="config" name="config" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="component" use="optional"/>
    </xs:complexType>
    <xs:complexType name="config">
        <xs:sequence>
            <xs:element type="item" name="item" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="item">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="value" use="optional"/>
    </xs:complexType>
    <xs:complexType name="element">
        <xs:choice maxOccurs="unbounded">
            <xs:element type="style" name="style" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="static_style" name="static_style" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="attribute" name="attribute" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="static_attribute" name="static_attribute" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="tag" name="tag" minOccurs="0" maxOccurs="1"/>
            <xs:element type="html" name="html" minOccurs="0" maxOccurs="1"/>
            <xs:element type="css" name="css" minOccurs="0" maxOccurs="1"/>
        </xs:choice>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>
    <xs:complexType name="additional_data">
        <xs:choice maxOccurs="unbounded">
            <xs:element type="argumentType" name="item" minOccurs="1" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="style">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="source" use="optional"/>
        <xs:attribute type="xs:string" name="converter" use="optional"/>
        <xs:attribute type="xs:string" name="preview_converter" use="optional"/>
        <xs:attribute type="xs:string" name="persistence_mode" use="optional"/>
        <xs:attribute type="xs:string" name="storage_key" use="optional"/>
        <xs:attribute type="xs:string" name="reader" use="optional"/>
    </xs:complexType>
    <xs:complexType name="static_style">
        <xs:attribute type="xs:string" name="source" use="required"/>
        <xs:attribute type="xs:string" name="value" use="optional"/>
    </xs:complexType>
    <xs:complexType name="attribute">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="source" use="optional"/>
        <xs:attribute type="xs:string" name="converter" use="optional"/>
        <xs:attribute type="xs:string" name="preview_converter" use="optional"/>
        <xs:attribute type="xs:string" name="persistence_mode" use="optional"/>
        <xs:attribute type="xs:string" name="storage_key" use="optional"/>
        <xs:attribute type="xs:string" name="reader" use="optional"/>
    </xs:complexType>
    <xs:complexType name="static_attribute">
        <xs:attribute type="xs:string" name="source" use="required"/>
        <xs:attribute type="xs:string" name="value" use="optional"/>
    </xs:complexType>
    <xs:complexType name="html">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="converter" use="optional"/>
        <xs:attribute type="xs:string" name="preview_converter" use="optional"/>
    </xs:complexType>
    <xs:complexType name="css">
        <xs:sequence>
            <xs:element type="filter" name="filter" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>
    <xs:complexType name="filter">
        <xs:sequence>
            <xs:element type="class" name="class" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="class">
        <xs:attribute type="xs:string" name="source" use="required"/>
    </xs:complexType>
    <xs:complexType name="tag">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="converter" use="optional"/>
    </xs:complexType>
</xs:schema>

=== AleksandrsKondratjevs/test-design-claude/app/code/Scandiweb/ContentTypes/view/adminhtml/pagebuilder/content_type/scandiweb_accordion.xml
<?xml version="1.0"?>
<!--
/**
 * @category  Scandiweb
 * @package   Scandiweb_ContentTypes
 * @author    Baron Gobi <info@scandiweb.com>
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_PageBuilder:etc/content_type.xsd">
    <type name="scandiweb_accordion" label="Accordion" menu_section="scandiweb_elements" component="Magento_PageBuilder/js/content-type" preview_component="Scandiweb_ContentTypes/js/content-type/accordion/preview" master_component="Magento_PageBuilder/js/content-type/master" form="pagebuilder_scandiweb_accordion_form" sortOrder="1" translate="label">
        <parents default_policy="deny">
            <parent name="row" policy="allow" />
            <parent name="column" policy="allow" />
            <parent name="tab-item" policy="allow"/>
            <parent name="scandiweb_tab_with_image_item" policy="allow"/>
        </parents>
        <children default_policy="deny" />
        <appearances>
            <appearance name="default" default="true" preview_template="Scandiweb_ContentTypes/content-type/accordion/default/preview" master_template="Scandiweb_ContentTypes/content-type/accordion/default/master" reader="Magento_PageBuilder/js/master-format/read/configurable">
                <elements>
                    <element name="main">
                        <style name="text_align" source="text_align" />
                        <style name="border" source="border_style" converter="Magento_PageBuilder/js/converter/style/border-style" />
                        <style name="border_color" source="border_color" />
                        <style name="border_width" source="border_width" converter="Magento_PageBuilder/js/converter/style/border-width" />
                        <style name="border_radius" source="border_radius" converter="Magento_PageBuilder/js/converter/style/remove-px" />
                        <style name="display" source="display" converter="Magento_PageBuilder/js/converter/style/display" preview_converter="Magento_PageBuilder/js/converter/style/preview/display" />
                        <style name="margins" storage_key="margins_and_padding" reader="Magento_PageBuilder/js/property/margins" converter="Magento_PageBuilder/js/converter/style/margins" />
                        <style name="padding" storage_key="margins_and_padding" reader="Magento_PageBuilder/js/property/paddings" converter="Magento_PageBuilder/js/converter/style/paddings" />
                        <attribute name="name" source="data-content-type" />
                        <attribute name="appearance" source="data-appearance" />
                        <attribute name="block_title" source="block_title" />
                        <attribute name="content" source="content" converter="Scandiweb_ContentTypes/js/content-type/accordion/converter/content" />
                        <attribute name="is_opened" source="is-opened" />
                        <attribute name="show_button" source="data-show-button"/>
                        <attribute name="desktop_disabled" source="desktop-disabled" />
                        <attribute name="title_color" source="title_color"/>
                        <css name="css_classes" />
                    </element>
                    <element name="block_title">
                        <html name="block_title" />
                    </element>
                    <element name="content">
                        <html name="content" preview_converter="Magento_PageBuilder/js/converter/html/directive" />
                    </element>
                    <element name="block_directive">
                        <html name="block_directive" converter="Magento_PageBuilder/js/converter/html/tag-escaper" />
                    </element>
                </elements>
                <converters>
                    <converter component="Scandiweb_ContentTypes/js/content-type/accordion/block-directive" name="block_directive">
                        <config>
                            <item name="html_variable" value="block_directive"/>
                            <item name="block_class" value="Scandiweb\ContentTypes\Block\ContentTypes\Accordion"/>
                        </config>
                    </converter>
                </converters>
            </appearance>
        </appearances>
        <additional_data>
            <item name="wysiwygConfig" xsi:type="array">
                <item name="wysiwygConfigData" xsi:type="object">
                    Magento\PageBuilder\Model\Config\ContentType\AdditionalData\Provider\Wysiwyg\Config
                </item>
            </item>
        </additional_data>
    </type>
</config>

=== AleksandrsKondratjevs/test-design-claude/app/code/Scandiweb/ContentTypes/view/adminhtml/pagebuilder/content_type/scandiweb_spacer.xml
<?xml version="1.0"?>
<!--
/**
 * @category  Scandiweb
 * @package   Scandiweb_ContentTypes
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_PageBuilder:etc/content_type.xsd">
    <type name="spacer" label="Spacer" component="Magento_PageBuilder/js/content-type"
        preview_component="Magento_PageBuilder/js/content-type/preview"
        master_component="Magento_PageBuilder/js/content-type/master"
        form="pagebuilder_scandiweb_spacer_form" menu_section="elements" sortOrder="0"
        translate="label"
>
        <children default_policy="deny" />
        <appearances>
            <appearance default="true" name="default"
                preview_template="Scandiweb_ContentTypes/content-type/spacer/default/preview"
                master_template="Scandiweb_ContentTypes/content-type/spacer/default/master"
                reader="Magento_PageBuilder/js/master-format/read/configurable">
                <elements>
                    <element name="main">
                        <attribute name="name" source="data-content-type"/>
                        <attribute name="appearance" source="data-appearance" />
                        <attribute name="space_mobile" source="space_mobile" />
                        <attribute name="space_desktop" source="space_desktop" />
                    </element>
                </elements>
            </appearance>
        </appearances>
    </type>
</config>

=== AleksandrsKondratjevs/test-design-claude/app/code/Scandiweb/ContentTypes/view/adminhtml/pagebuilder/content_type/scandiweb_tabs_with_image.xml
<?xml version="1.0"?>
<!--
/**
 * @category  Scandiweb
 * @package   Scandiweb_ContentTypes
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_PageBuilder:etc/content_type.xsd">
    <type name="scandiweb_tabs_with_image"
          label="Tabs With Image"
          component="Magento_PageBuilder/js/content-type-collection"
          preview_component="Scandiweb_ContentTypes/js/content-type/tabs-with-image/preview"
          master_component="Magento_PageBuilder/js/content-type/master-collection"
          form="pagebuilder_scandiweb_tabs_with_image_form"
          menu_section="layout"
          icon="icon-pagebuilder-tabs"
          sortOrder="25"
          translate="label">
        <breakpoints>
            <breakpoint name="mobile">
                <form>pagebuilder_scandiweb_tabs_with_image_mobile_form</form>
            </breakpoint>
        </breakpoints>
        <parents default_policy="deny">
            <parent name="root-container" policy="allow"/>
            <parent name="row" policy="allow"/>
            <parent name="column" policy="allow"/>
        </parents>
        <children default_policy="deny">
            <child name="scandiweb_tab_with_image_item" policy="allow"/>
        </children>
        <appearances>
            <appearance name="default"
                        default="true"
                        preview_template="Scandiweb_ContentTypes/content-type/tabs-with-image/default/preview"
                        master_template="Scandiweb_ContentTypes/content-type/tabs-with-image/default/master"
                        reader="Magento_PageBuilder/js/master-format/read/configurable">
                <elements>
                    <element name="main">
                        <style name="display" source="display" converter="Magento_PageBuilder/js/converter/style/display" preview_converter="Magento_PageBuilder/js/converter/style/preview/display"/>
                        <style name="margins" storage_key="margins_and_padding" reader="Magento_PageBuilder/js/property/margins" converter="Magento_PageBuilder/js/converter/style/margins"/>
                        <style name="padding" storage_key="margins_and_padding" reader="Magento_PageBuilder/js/property/paddings" converter="Magento_PageBuilder/js/converter/style/paddings"/>
                        <attribute name="block_title" source="data-block-title"/>
                        <attribute name="block_subtitle" source="data-block-subtitle"/>
                        <attribute name="tab_color" source="data-background_color" />
                        <attribute name="name" source="data-content-type"/>
                        <attribute name="appearance" source="data-appearance"/>
                        <attribute name="default_active" source="data-active-tab"/>
                        <css name="css_classes">
                            <filter>
                                <class source="tab-align-left"/>
                                <class source="tab-align-center"/>
                                <class source="tab-align-right"/>
                            </filter>
                        </css>
                    </element>
                    <element name="background">
                        <style name="tab_color" source="background_color" />
                    </element>
                    <element name="headers">
                        <style name="border" source="border_style" converter="Magento_PageBuilder/js/converter/style/border-style"/>
                        <style name="border_radius" source="border_radius" converter="Magento_PageBuilder/js/converter/style/remove-px"/>
                        <style name="border_color" source="border_color"/>
                        <style name="border_width" source="border_width" converter="Magento_PageBuilder/js/converter/style/remove-px"/>
                    </element>
                    <element name="navigation">
                        <style name="navigation_alignment" source="text_align"/>
                    </element>
                    <element name="content">
                        <style name="border" source="border_style" converter="Magento_PageBuilder/js/converter/style/border-style"/>
                        <style name="text_align" source="text_align"/>
                        <style name="border_color" source="border_color"/>
                        <style name="border_width" source="border_width" converter="Magento_PageBuilder/js/converter/style/remove-px"/>
                        <style name="border_radius" source="border_radius" converter="Magento_PageBuilder/js/converter/style/remove-px"/>
                        <style name="min_height" source="min_height" converter="Magento_PageBuilder/js/converter/style/remove-px"/>
                        <style name="tab_color" source="background_color" />
                    </element>
                </elements>
                <converters>
                    <converter name="header_alignment_class" component="Magento_PageBuilder/js/content-type/tabs/mass-converter/header-alignment">
                        <config>
                            <item name="navigation_alignment_variable" value="navigation_alignment"/>
                        </config>
                    </converter>
                </converters>
            </appearance>
            <appearance name="full-width"
                        default="false"
                        preview_template="Scandiweb_ContentTypes/content-type/tabs-with-image/full-width/preview"
                        master_template="Scandiweb_ContentTypes/content-type/tabs-with-image/full-width/master"
                        reader="Magento_PageBuilder/js/master-format/read/configurable">
                <elements>
                    <element name="main">
                        <style name="display" source="display" converter="Magento_PageBuilder/js/converter/style/display" preview_converter="Magento_PageBuilder/js/converter/style/preview/display"/>
                        <style name="margins" storage_key="margins_and_padding" reader="Magento_PageBuilder/js/property/margins" converter="Magento_PageBuilder/js/converter/style/margins"/>
                        <style name="padding" storage_key="margins_and_padding" reader="Magento_PageBuilder/js/property/paddings" converter="Magento_PageBuilder/js/converter/style/paddings"/>
                        <attribute name="block_title" source="data-block-title"/>
                        <attribute name="block_subtitle" source="data-block-subtitle"/>
                        <attribute name="tab_color" source="data-background_color" />
                        <attribute name="name" source="data-content-type"/>
                        <attribute name="appearance" source="data-appearance"/>
                        <attribute name="default_active" source="data-active-tab"/>
                        <css name="css_classes">
                            <filter>
                                <class source="tab-align-left"/>
                                <class source="tab-align-center"/>
                                <class source="tab-align-right"/>
                            </filter>
                        </css>
                    </element>
                    <element name="background">
                        <style name="tab_color" source="background_color" />
                    </element>
                    <element name="headers">
                        <style name="border" source="border_style" converter="Magento_PageBuilder/js/converter/style/border-style"/>
                        <style name="border_radius" source="border_radius" converter="Magento_PageBuilder/js/converter/style/remove-px"/>
                        <style name="border_color" source="border_color"/>
                        <style name="border_width" source="border_width" converter="Magento_PageBuilder/js/converter/style/remove-px"/>
                    </element>
                    <element name="navigation">
                        <style name="navigation_alignment" source="text_align"/>
                    </element>
                    <element name="content">
                        <style name="border" source="border_style" converter="Magento_PageBuilder/js/converter/style/border-style"/>
                        <style name="text_align" source="text_align"/>
                        <style name="border_color" source="border_color"/>
                        <style name="border_width" source="border_width" converter="Magento_PageBuilder/js/converter/style/remove-px"/>
                        <style name="border_radius" source="border_radius" converter="Magento_PageBuilder/js/converter/style/remove-px"/>
                        <style name="min_height" source="min_height" converter="Magento_PageBuilder/js/converter/style/remove-px"/>
                        <style name="tab_color" source="background_color" />
                    </element>
                </elements>
                <converters>
                    <converter name="header_alignment_class" component="Magento_PageBuilder/js/content-type/tabs/mass-converter/header-alignment">
                        <config>
                            <item name="navigation_alignment_variable" value="navigation_alignment"/>
                        </config>
                    </converter>
                </converters>
            </appearance>
        </appearances>
    </type>
</config>
