=== AleksandrsKondratjevs/test-design-claude/app/code/Scandiweb/ContentTypes/etc/content_type.xsd
<?xml version="1.0"?>
<!--
/**
 * @category  Scandiweb
 * @package   Scandiweb_ContentTypes
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:redefine schemaLocation="urn:magento:framework:Data/etc/argument/types.xsd"/>
    <xs:element name="config">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="type" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element type="xs:string" name="preview_template" minOccurs="0"/>
                            <xs:element type="xs:string" name="master_template" minOccurs="0"/>
                            <xs:element type="parents" name="parents" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="breakpoints" name="breakpoints" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="children" name="children" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="appearances" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="appearance" name="appearance" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="additional_data" name="additional_data" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="xs:string" name="is_system" minOccurs="0"/>
                        </xs:all>
                        <xs:attribute type="xs:string" name="name" use="required"/>
                        <xs:attribute type="xs:string" name="translate" use="optional"/>
                        <xs:attribute type="xs:byte" name="sortOrder" use="optional"/>
                        <xs:attribute type="xs:string" name="label" use="optional"/>
                        <xs:attribute type="xs:string" name="icon" use="optional"/>
                        <xs:attribute type="xs:string" name="component" use="optional"/>
                        <xs:attribute type="xs:string" name="preview_component" use="optional"/>
                        <xs:attribute type="xs:string" name="master_component" use="optional"/>
                        <xs:attribute type="xs:string" name="form" use="optional"/>
                        <xs:attribute type="xs:string" name="menu_section" use="optional"/>
                        <!-- Added additional attribute for passing block class -->
                        <xs:attribute type="xs:string" name="backend_block" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="appearance">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="data" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="name"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element type="elements" name="elements" minOccurs="0" maxOccurs="1"/>
            <xs:element type="converters" name="converters" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="form" minOccurs="0" maxOccurs="1"/>
            <xs:element type="breakpoints" name="breakpoints" minOccurs="0" maxOccurs="1"/>
        </xs:choice>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:boolean" name="default" use="optional"/>
        <xs:attribute type="xs:string" name="preview_template" use="optional"/>
        <xs:attribute type="xs:string" name="master_template" use="optional"/>
        <xs:attribute type="xs:string" name="reader" use="optional"/>
    </xs:complexType>
    <xs:complexType name="parents">
        <xs:sequence>
            <xs:element type="parent" name="parent" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="default_policy" use="optional"/>
    </xs:complexType>
    <xs:complexType name="breakpoints">
        <xs:sequence>
            <xs:element type="breakpoint" name="breakpoint" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="children">
        <xs:sequence>
            <xs:element type="child" name="child" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="default_policy" use="optional"/>
    </xs:complexType>
    <xs:complexType name="parent">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="policy" use="optional"/>
    </xs:complexType>
    <xs:complexType name="breakpoint">
        <xs:choice maxOccurs="unbounded">
            <xs:element type="xs:string" name="form" minOccurs="0" maxOccurs="1"/>
        </xs:choice>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>
    <xs:complexType name="child">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="policy" use="optional"/>
    </xs:complexType>
    <xs:complexType name="elements">
        <xs:sequence>
            <xs:element type="element" name="element" minOccurs="1" maxOccurs="unbounded">
                <xs:unique name="uniqueNames">
                    <xs:annotation>
                        <xs:documentation>
                            Attribute and Style names must be unique
                        </xs:documentation>
                    </xs:annotation>
                    <xs:selector xpath="attribute|style"/>
                    <xs:field xpath="@name"/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="converters">
        <xs:sequence>
            <xs:element type="converter" name="converter" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="converter">
        <xs:sequence>
            <xs:element type="config" name="config" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="component" use="optional"/>
    </xs:complexType>
    <xs:complexType name="config">
        <xs:sequence>
            <xs:element type="item" name="item" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="item">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="value" use="optional"/>
    </xs:complexType>
    <xs:complexType name="element">
        <xs:choice maxOccurs="unbounded">
            <xs:element type="style" name="style" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="static_style" name="static_style" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="attribute" name="attribute" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="static_attribute" name="static_attribute" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="tag" name="tag" minOccurs="0" maxOccurs="1"/>
            <xs:element type="html" name="html" minOccurs="0" maxOccurs="1"/>
            <xs:element type="css" name="css" minOccurs="0" maxOccurs="1"/>
        </xs:choice>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>
    <xs:complexType name="additional_data">
        <xs:choice maxOccurs="unbounded">
            <xs:element type="argumentType" name="item" minOccurs="1" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="style">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="source" use="optional"/>
        <xs:attribute type="xs:string" name="converter" use="optional"/>
        <xs:attribute type="xs:string" name="preview_converter" use="optional"/>
        <xs:attribute type="xs:string" name="persistence_mode" use="optional"/>
        <xs:attribute type="xs:string" name="storage_key" use="optional"/>
        <xs:attribute type="xs:string" name="reader" use="optional"/>
    </xs:complexType>
    <xs:complexType name="static_style">
        <xs:attribute type="xs:string" name="source" use="required"/>
        <xs:attribute type="xs:string" name="value" use="optional"/>
    </xs:complexType>
    <xs:complexType name="attribute">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="source" use="optional"/>
        <xs:attribute type="xs:string" name="converter" use="optional"/>
        <xs:attribute type="xs:string" name="preview_converter" use="optional"/>
        <xs:attribute type="xs:string" name="persistence_mode" use="optional"/>
        <xs:attribute type="xs:string" name="storage_key" use="optional"/>
        <xs:attribute type="xs:string" name="reader" use="optional"/>
    </xs:complexType>
    <xs:complexType name="static_attribute">
        <xs:attribute type="xs:string" name="source" use="required"/>
        <xs:attribute type="xs:string" name="value" use="optional"/>
    </xs:complexType>
    <xs:complexType name="html">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="converter" use="optional"/>
        <xs:attribute type="xs:string" name="preview_converter" use="optional"/>
    </xs:complexType>
    <xs:complexType name="css">
        <xs:sequence>
            <xs:element type="filter" name="filter" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>
    <xs:complexType name="filter">
        <xs:sequence>
            <xs:element type="class" name="class" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="class">
        <xs:attribute type="xs:string" name="source" use="required"/>
    </xs:complexType>
    <xs:complexType name="tag">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="converter" use="optional"/>
    </xs:complexType>
</xs:schema>

=== AleksandrsKondratjevs/test-design-claude/app/code/Scandiweb/ContentTypes/view/adminhtml/pagebuilder/content_type/scandiweb_slider.xml
<?xml version="1.0"?>
<!--
/**
 * @category  Scandiweb
 * @package   Scandiweb_ContentTypes
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_PageBuilder:etc/content_type.xsd">
    <type name="slider" icon="" label="Slider" component="Magento_PageBuilder/js/content-type-collection" preview_component="Magento_PageBuilder/js/content-type/slider/preview" master_component="Magento_PageBuilder/js/content-type/master-collection" form="pagebuilder_scandiweb_slider_form" menu_section="scandiweb_components" sortOrder="41" translate="label">
        <breakpoints>
            <breakpoint name="mobile">
                <form>pagebuilder_scandiweb_slider_mobile_form</form>
            </breakpoint>
        </breakpoints>
        <children default_policy="deny">
            <child name="slide" policy="allow"/>
        </children>
        <appearances>
            <appearance default="true" name="default" preview_template="Magento_PageBuilder/content-type/slider/default/preview" master_template="Magento_PageBuilder/content-type/slider/default/master" reader="Magento_PageBuilder/js/master-format/read/configurable">
                <elements>
                    <element name="main">
                        <style name="text_align" source="text_align"/>
                        <style name="min_height" source="min_height" converter="Magento_PageBuilder/js/converter/style/min-height"/>
                        <style name="border" source="border_style" converter="Magento_PageBuilder/js/converter/style/border-style"/>
                        <style name="border_color" source="border_color"/>
                        <style name="border_width" source="border_width" converter="Magento_PageBuilder/js/converter/style/border-width"/>
                        <style name="border_radius" source="border_radius" converter="Magento_PageBuilder/js/converter/style/remove-px"/>
                        <style name="display" source="display" converter="Magento_PageBuilder/js/converter/style/display" preview_converter="Magento_PageBuilder/js/converter/style/preview/display"/>
                        <style name="margins" storage_key="margins_and_padding" reader="Magento_PageBuilder/js/property/margins" converter="Magento_PageBuilder/js/converter/style/margins"/>
                        <style name="padding" storage_key="margins_and_padding" reader="Magento_PageBuilder/js/property/paddings" converter="Magento_PageBuilder/js/converter/style/paddings"/>
                        <attribute name="name" source="data-content-type"/>
                        <attribute name="appearance" source="data-appearance"/>
                        <attribute name="autoplay" source="data-autoplay"/>
                        <attribute name="autoplay_speed" source="data-autoplay-speed"/>
                        <attribute name="fade" source="data-fade"/>
                        <attribute name="is_infinite" source="data-infinite-loop"/>
                        <attribute name="show_arrows" source="data-show-arrows"/>
                        <attribute name="show_dots" source="data-show-dots"/>
                        <css name="css_classes"/>
                    </element>
                </elements>
            </appearance>
        </appearances>
    </type>
</config>

=== AleksandrsKondratjevs/test-design-claude/app/code/Scandiweb/ContentTypes/view/adminhtml/pagebuilder/content_type/scandiweb_featured_block.xml
<?xml version="1.0"?>
<!--
/**
 * @category  Scandiweb
 * @package   Scandiweb_ContentTypes
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_PageBuilder:etc/content_type.xsd">
    <type name="scandiweb_featured_block" label="Featured Block" menu_section="scandiweb_components"
        component="Magento_PageBuilder/js/content-type"
        backend_block="Scandiweb\ContentTypes\Block\ContentTypes\FeaturedBlock"
        preview_component="Scandiweb_ContentTypes/js/content-type/featured-block/preview"
        master_component="Magento_PageBuilder/js/content-type/master"
        form="pagebuilder_scandiweb_featured_block_form" sortOrder="3" translate="label">
        <children default_policy="deny" />
        <parents default_policy="deny">
            <parent name="row" policy="allow" />
            <parent name="column" policy="allow" />
            <parent name="tab-item" policy="allow" />
            <parent name="scandiweb_tab_with_image_item" policy="allow" />
        </parents>
        <appearances>
            <appearance name="default" default="true"
                preview_template="Scandiweb_ContentTypes/content-type/featured-block/default/preview"
                master_template="Scandiweb_ContentTypes/content-type/featured-block/default/master"
                reader="Magento_PageBuilder/js/master-format/read/configurable">
                <elements>
                    <element name="main">
                        <attribute name="name" source="data-content-type" />
                        <attribute name="appearance" source="data-appearance" />
                        <attribute name="content_title" source="content_title" />
                        <attribute name="content_description" source="content_description" />
                        <attribute name="show_first_cta" source="show_first_cta" />
                        <attribute name="first_cta_text" source="first_cta_text" />
                        <attribute name="first_cta_link" source="first_cta_link" converter="Scandiweb_ContentTypes/js/converter/attribute/object" />
                        <attribute name="first_cta_type" source="first_cta_type" />
                        <attribute name="show_second_cta" source="show_second_cta" />
                        <attribute name="second_cta_text" source="second_cta_text" />
                        <attribute name="second_cta_link" source="second_cta_link" converter="Scandiweb_ContentTypes/js/converter/attribute/object" />
                        <attribute name="second_cta_type" source="second_cta_type" />
                        <attribute name="visual_content_position" source="visual_content_position" />
                        <attribute name="visual_content_img" source="src"
                            converter="Magento_PageBuilder/js/converter/attribute/src"
                            preview_converter="Magento_PageBuilder/js/converter/attribute/preview/src" />
                        <attribute name="visual_content_mobile_img" source="mobile_src"
                            converter="Magento_PageBuilder/js/converter/attribute/src"
                            preview_converter="Magento_PageBuilder/js/converter/attribute/preview/src" />
                        <html name="html" />
                    </element>
                </elements>
				<converters>
					<converter
						component="Scandiweb_ContentTypes/js/content-type/featured-block/mass-converter/block-directive"
						name="block_directive">
						<config>
							<item name="html_variable" value="html" />
						</config>
					</converter>
				</converters>
            </appearance>
        </appearances>
    </type>
</config>

=== AleksandrsKondratjevs/test-design-claude/app/code/Scandiweb/ContentTypes/view/adminhtml/pagebuilder/content_type/scandiweb_read_more_text.xml
<?xml version="1.0"?>
<!--
/**
 * @category  Scandiweb
 * @package   Scandiweb_ContentTypes
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_PageBuilder:etc/content_type.xsd">
    <type name="read_more_text" label="Read more Text" component="Magento_PageBuilder/js/content-type" preview_component="Magento_PageBuilder/js/content-type/text/preview" form="pagebuilder_scandiweb_read_more_text_form" menu_section="scandiweb_elements" sortOrder="2" translate="label">
        <children default_policy="deny"/>
        <appearances>
            <appearance default="true" name="default" preview_template="Magento_PageBuilder/content-type/text/default/preview" master_template="Scandiweb_ContentTypes/content-type/read-more-text/default/master" reader="Magento_PageBuilder/js/master-format/read/configurable">
                <elements>
                    <element name="main">
                        <style name="text_align" source="text_align"/>
                        <style name="border" source="border_style" converter="Magento_PageBuilder/js/converter/style/border-style"/>
                        <style name="border_color" source="border_color"/>
                        <style name="border_width" source="border_width" converter="Magento_PageBuilder/js/converter/style/border-width"/>
                        <style name="border_radius" source="border_radius" converter="Magento_PageBuilder/js/converter/style/remove-px"/>
                        <style name="display" source="display" converter="Magento_PageBuilder/js/converter/style/display" preview_converter="Magento_PageBuilder/js/converter/style/preview/display"/>
                        <style name="margins" storage_key="margins_and_padding" reader="Magento_PageBuilder/js/property/margins" converter="Magento_PageBuilder/js/converter/style/margins"/>
                        <style name="padding" storage_key="margins_and_padding" reader="Magento_PageBuilder/js/property/paddings" converter="Magento_PageBuilder/js/converter/style/paddings"/>
                        <attribute name="name" source="data-content-type"/>
                        <attribute name="appearance" source="data-appearance"/>
                        <attribute name="truncate_desktop" source="truncate_desktop"/>
                        <attribute name="truncate_desktop_lines" source="truncate_desktop_lines"/>
                        <attribute name="truncate_mobile" source="truncate_mobile"/>
                        <attribute name="truncate_mobile_lines" source="truncate_mobile_lines"/>
                        <html name="content" preview_converter="Magento_PageBuilder/js/converter/html/directive"/>
                        <css name="css_classes"/>
                    </element>
                </elements>
            </appearance>
        </appearances>
        <additional_data>
            <item name="wysiwygConfig" xsi:type="array">
                <item name="wysiwygConfigData" xsi:type="object">Magento\PageBuilder\Model\Config\ContentType\AdditionalData\Provider\Wysiwyg\Config</item>
            </item>
        </additional_data>
    </type>
</config>

=== AleksandrsKondratjevs/test-design-claude/app/code/Scandiweb/ContentTypes/view/adminhtml/pagebuilder/content_type/scandiweb_featured_categories.xml
<?xml version="1.0"?>
<!--
/**
 * @category  Scandiweb
 * @package   Scandiweb_ContentTypes
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_PageBuilder:etc/content_type.xsd">
	<type name="scandiweb_featured_categories" label="Featured Categories"
		backend_block="Scandiweb\ContentTypes\Block\ContentTypes\FeaturedCategories"
		menu_section="scandiweb_components" component="Magento_PageBuilder/js/content-type"
		preview_component="Scandiweb_ContentTypes/js/content-type/featured-categories/preview"
		master_component="Magento_PageBuilder/js/content-type/master"
		form="pagebuilder_scandiweb_featured_categories_form" sortOrder="4" translate="label">
		<children default_policy="deny" />
		<parents default_policy="allow">
			<parent name="row" policy="allow" />
			<parent name="column" policy="allow" />
			<parent name="tab-item" policy="allow" />
			<parent name="scandiweb_tab_with_image_item" policy="allow" />
		</parents>
		<appearances>
			<appearance name="default" default="true"
				preview_template="Scandiweb_ContentTypes/content-type/featured-categories/default/preview"
				master_template="Scandiweb_ContentTypes/content-type/featured-categories/default/master"
				reader="Magento_PageBuilder/js/master-format/read/configurable">
				<elements>
					<element name="main">
						<attribute name="name" source="data-content-type" />
						<attribute name="appearance" source="data-appearance" />
						<attribute name="appearance_type" source="appearance_type" />
						<attribute name="block_title" source="block_title" />
						<attribute name="block_sub_title" source="block_sub_title" />
						<attribute name="slider_infinitive" source="slider_infinitive" />
						<attribute name="slider_pagination" source="slider_pagination" />
						<attribute name="slider_show_arrows" source="slider_show_arrows" />
						<attribute name="slider_count_mobile" source="slider_count_mobile" />
						<attribute name="slider_count_tablet" source="slider_count_tablet" />
						<attribute name="slider_count_desktop" source="slider_count_desktop" />
						<attribute name="grid_columns_mobile" source="grid_columns_mobile" />
						<attribute name="grid_columns_tablet" source="grid_columns_tablet" />
						<attribute name="grid_columns_desktop" source="grid_columns_desktop" />
						<attribute name="sections" source="data-sections"
							converter="Scandiweb_ContentTypes/js/converter/attribute/object" />
						<html name="html" />
					</element>
				</elements>
				<converters>
					<converter
						component="Scandiweb_ContentTypes/js/content-type/featured-categories/mass-converter/block-directive"
						name="block_directive">
						<config>
							<item name="html_variable" value="html" />
						</config>
					</converter>
				</converters>
			</appearance>
		</appearances>
	</type>
</config>
